const ProductData = [
  {
    id: 1,
    title: "REDMI 9 Prime (Mint Green, 64 GB)  (4 GB RAM)",
    price: 10499,
    image: "/image/p1.jpeg",
    category: "redmi",
    details:
      "4 GB RAM | 64 GB ROM | Expandable Upto 512 GB 16.59 cm (6.53 inch) HD+ Display 13MP Rear Camera | 5MP Front Camera 5000 mAh Li-Polymer BatteryMediaTek Helio G2 Processor",
    image1: "/image/sm1.jpeg",
    image2: "/image/sm2.jpeg",
    image3: "/image/sm3.jpeg",
    image4: "/image/sm4.jpeg",
    quantity: 1,
  },
  {
    id: 2,
    title: "REDMI 9i (Nature Green, 64 GB)  (4 GB RAM)",
    price: 8999,
    image: "/image/p2.jpeg",
    category: "redmi",
    details:
      "4 GB RAM | 64 GB ROM | Expandable Upto 512 GB 16.59 cm (6.53 inch) HD+ Display 13MP Rear Camera | 5MP Front Camera 5000 mAh Li-Polymer BatteryMediaTek Helio G2 Processor",
    image1: "/image/sm1.jpeg",
    image2: "/image/sm2.jpeg",
    image3: "/image/sm3.jpeg",
    image4: "/image/sm4.jpeg",
    quantity: 1,
  },
  {
    id: 3,
    title: "REDMI 9 Power (Blazing Blue, 64 GB)  (4 GB RAM)",
    price: 11499,
    image: "/image/p3.jpeg",
    category: "redmi",
    details:
      "4 GB RAM | 64 GB ROM | Expandable Upto 512 GB 16.59 cm (6.53 inch) HD+ Display 13MP Rear Camera | 5MP Front Camera 5000 mAh Li-Polymer BatteryMediaTek Helio G2 Processor",
    image1: "/image/sm1.jpeg",
    image2: "/image/sm2.jpeg",
    image3: "/image/sm3.jpeg",
    image4: "/image/sm4.jpeg",
    quantity: 1,
  },
  {
    id: 4,
    title: "REDMI Note 10S (Shadow Black, 64 GB)  (6 GB RAM)",
    price: 15715,
    image: "/image/p4.jpeg",
    category: "redmi",
    details:
      "4 GB RAM | 64 GB ROM | Expandable Upto 512 GB 16.59 cm (6.53 inch) HD+ Display 13MP Rear Camera | 5MP Front Camera 5000 mAh Li-Polymer BatteryMediaTek Helio G2 Processor",
    image1: "/image/sm1.jpeg",
    image2: "/image/sm2.jpeg",
    image3: "/image/sm3.jpeg",
    image4: "/image/sm4.jpeg",
    quantity: 1,
  },
  {
    id: 5,
    title: "REDMI 10 Prime (Phantom Black, 64 GB)  (4 GB RAM)",
    price: 14768,
    image: "/image/p5.jpeg",
    category: "redmi",
    details:
      "4 GB RAM | 64 GB ROM | Expandable Upto 512 GB 16.59 cm (6.53 inch) HD+ Display 13MP Rear Camera | 5MP Front Camera 5000 mAh Li-Polymer BatteryMediaTek Helio G2 Processor",
    image1: "/image/sm1.jpeg",
    image2: "/image/sm2.jpeg",
    image3: "/image/sm3.jpeg",
    image4: "/image/sm4.jpeg",
    quantity: 1,
  },
  {
    id: 6,
    title: "REDMI Note 9 (Arctic White, 128 GB)  (6 GB RAM)",
    price: 16969,
    image: "/image/p6.jpeg",
    category: "redmi",
    details:
      "4 GB RAM | 64 GB ROM | Expandable Upto 512 GB 16.59 cm (6.53 inch) HD+ Display 13MP Rear Camera | 5MP Front Camera 5000 mAh Li-Polymer BatteryMediaTek Helio G2 Processor",
    image1: "/image/sm1.jpeg",
    image2: "/image/sm2.jpeg",
    image3: "/image/sm3.jpeg",
    image4: "/image/sm4.jpeg",
    quantity: 1,
  },
  {
    id: 7,
    title: "REDMI Note 10T 5G (Graphite Black, 64 GB)  (4 GB RAM)",
    price: 16245,
    image: "/image/p7.jpeg",
    category: "redmi",
    details:
      "4 GB RAM | 64 GB ROM | Expandable Upto 512 GB 16.59 cm (6.53 inch) HD+ Display 13MP Rear Camera | 5MP Front Camera 5000 mAh Li-Polymer BatteryMediaTek Helio G2 Processor",
    image1: "/image/sm1.jpeg",
    image2: "/image/sm2.jpeg",
    image3: "/image/sm3.jpeg",
    image4: "/image/sm4.jpeg",
    quantity: 1,
  },
  {
    id: 8,
    title: "REDMI 8A Dual (Sea Blue, 32 GB)  (2 GB RAM)",
    price: 8999,
    image: "/image/p8.jpeg",
    category: "redmi",
    details:
      "4 GB RAM | 64 GB ROM | Expandable Upto 512 GB 16.59 cm (6.53 inch) HD+ Display 13MP Rear Camera | 5MP Front Camera 5000 mAh Li-Polymer BatteryMediaTek Helio G2 Processor",
    image1: "/image/sm1.jpeg",
    image2: "/image/sm2.jpeg",
    image3: "/image/sm3.jpeg",
    image4: "/image/sm4.jpeg",
    quantity: 1,
  },
  {
    id: 9,
    title: "REDMI Note 10 Pro Max (Vintage Bronze, 128 GB)  (8 GB RAM)",
    price: 24000,
    image: "/image/p9.jpeg",
    category: "redmi",
    details:
      "4 GB RAM | 64 GB ROM | Expandable Upto 512 GB 16.59 cm (6.53 inch) HD+ Display 13MP Rear Camera | 5MP Front Camera 5000 mAh Li-Polymer BatteryMediaTek Helio G2 Processor",
    image1: "/image/sm1.jpeg",
    image2: "/image/sm2.jpeg",
    image3: "/image/sm3.jpeg",
    image4: "/image/sm4.jpeg",
    quantity: 1,
  },
  {
    id: 10,
    title: "SAMSUNG Galaxy F22 (Denim Blue, 128 GB)  (6 GB RAM)",
    price: 14999,
    image: "/image/p10.jpeg",
    category: "samsung            ",
    details:
      "4 GB RAM | 64 GB ROM | Expandable Upto 512 GB 16.59 cm (6.53 inch) HD+ Display 13MP Rear Camera | 5MP Front Camera 5000 mAh Li-Polymer BatteryMediaTek Helio G2 Processor",
    image1: "/image/sm1.jpeg",
    image2: "/image/sm2.jpeg",
    image3: "/image/sm3.jpeg",
    image4: "/image/sm4.jpeg",
    quantity: 1,
  },
  {
    id: 11,
    title: "SAMSUNG Galaxy F12 (Sky Blue, 64 GB)  (4 GB RAM)",
    price: 11499,
    image: "/image/p11.jpeg",
    category: "samsung            ",
    details:
      "4 GB RAM | 64 GB ROM | Expandable Upto 512 GB 16.59 cm (6.53 inch) HD+ Display 13MP Rear Camera | 5MP Front Camera 5000 mAh Li-Polymer BatteryMediaTek Helio G2 Processor",
    image1: "/image/sm1.jpeg",
    image2: "/image/sm2.jpeg",
    image3: "/image/sm3.jpeg",
    image4: "/image/sm4.jpeg",
    quantity: 1,
  },
  {
    id: 12,
    title: "SAMSUNG Galaxy M12 (Black, 64 GB)  (4 GB RAM)",
    price: 11399,
    image: "/image/p12.jpeg",
    category: "samsung            ",
    details:
      "4 GB RAM | 64 GB ROM | Expandable Upto 512 GB 16.59 cm (6.53 inch) HD+ Display 13MP Rear Camera | 5MP Front Camera 5000 mAh Li-Polymer BatteryMediaTek Helio G2 Processor",
    image1: "/image/sm1.jpeg",
    image2: "/image/sm2.jpeg",
    image3: "/image/sm3.jpeg",
    image4: "/image/sm4.jpeg",
    quantity: 1,
  },
  {
    id: 13,
    title: "SAMSUNG M31 (Ocean Blue, 128 GB)  (6 GB RAM)",
    price: 16990,
    image: "/image/p13.jpeg",
    category: "samsung            ",
    details:
      "4 GB RAM | 64 GB ROM | Expandable Upto 512 GB 16.59 cm (6.53 inch) HD+ Display 13MP Rear Camera | 5MP Front Camera 5000 mAh Li-Polymer BatteryMediaTek Helio G2 Processor",
    image1: "/image/sm1.jpeg",
    image2: "/image/sm2.jpeg",
    image3: "/image/sm3.jpeg",
    image4: "/image/sm4.jpeg",
    quantity: 1,
  },
  {
    id: 14,
    title: "SAMSUNG Guru FM Plus SM-B110E/D  (Dark Blue)",
    price: 1750,
    image: "/image/p14.jpeg",
    category: "samsung            ",
    details:
      "4 GB RAM | 64 GB ROM | Expandable Upto 512 GB 16.59 cm (6.53 inch) HD+ Display 13MP Rear Camera | 5MP Front Camera 5000 mAh Li-Polymer BatteryMediaTek Helio G2 Processor",
    image1: "/image/sm1.jpeg",
    image2: "/image/sm2.jpeg",
    image3: "/image/sm3.jpeg",
    image4: "/image/sm4.jpeg",
    quantity: 1,
  },
  {
    id: 15,
    title: "SAMSUNG Galaxy A22 (Black, 128 GB)  (6 GB RAM)",
    price: 18499,
    image: "/image/p15.jpeg",
    category: "samsung            ",
    details:
      "4 GB RAM | 64 GB ROM | Expandable Upto 512 GB 16.59 cm (6.53 inch) HD+ Display 13MP Rear Camera | 5MP Front Camera 5000 mAh Li-Polymer BatteryMediaTek Helio G2 Processor",
    image1: "/image/sm1.jpeg",
    image2: "/image/sm2.jpeg",
    image3: "/image/sm3.jpeg",
    image4: "/image/sm4.jpeg",
    quantity: 1,
  },
  {
    id: 16,
    title: "SAMSUNG M31s (Mirage Blue, 128 GB)  (8 GB RAM)",
    price: 20990,
    image: "/image/p16.jpeg",
    category: "samsung            ",
    details:
      "4 GB RAM | 64 GB ROM | Expandable Upto 512 GB 16.59 cm (6.53 inch) HD+ Display 13MP Rear Camera | 5MP Front Camera 5000 mAh Li-Polymer BatteryMediaTek Helio G2 Processor",
    image1: "/image/sm1.jpeg",
    image2: "/image/sm2.jpeg",
    image3: "/image/sm3.jpeg",
    image4: "/image/sm4.jpeg",
    quantity: 1,
  },
  {
    id: 17,
    title: "SAMSUNG Galaxy M02 (Blue, 32 GB)  (2 GB RAM)",
    price: 8799,
    image: "/image/p17.jpeg",
    category: "samsung            ",
    details:
      "4 GB RAM | 64 GB ROM | Expandable Upto 512 GB 16.59 cm (6.53 inch) HD+ Display 13MP Rear Camera | 5MP Front Camera 5000 mAh Li-Polymer BatteryMediaTek Helio G2 Processor",
    image1: "/image/sm1.jpeg",
    image2: "/image/sm2.jpeg",
    image3: "/image/sm3.jpeg",
    image4: "/image/sm4.jpeg",
    quantity: 1,
  },
  {
    id: 18,
    title: "SAMSUNG Galaxy A52s 5G (Awesome White, 128 GB)  (8 GB RAM)",
    price: 37499,
    image: "/image/p18.jpeg",
    category: "samsung            ",
    details:
      "4 GB RAM | 64 GB ROM | Expandable Upto 512 GB 16.59 cm (6.53 inch) HD+ Display 13MP Rear Camera | 5MP Front Camera 5000 mAh Li-Polymer BatteryMediaTek Helio G2 Processor",
    image1: "/image/sm1.jpeg",
    image2: "/image/sm2.jpeg",
    image3: "/image/sm3.jpeg",
    image4: "/image/sm4.jpeg",
    quantity: 1,
  },
  {
    id: 19,
    title: "OPPO A53 (Moonlight Black, 64 GB)  (4 GB RAM)",
    price: 11990,
    image: "/image/p19.jpeg",
    category: "oppo",
    details:
      "4 GB RAM | 64 GB ROM | Expandable Upto 512 GB 16.59 cm (6.53 inch) HD+ Display 13MP Rear Camera | 5MP Front Camera 5000 mAh Li-Polymer BatteryMediaTek Helio G25 Processor",
    image1: "/image/sm1.jpeg",
    image2: "/image/sm2.jpeg",
    image3: "/image/sm3.jpeg",
    image4: "/image/sm4.jpeg",
    quantity: 1,
  },
  {
    id: 20,
    title: "OPPO A12 (Flowing Silver, 64 GB)  (4 GB RAM)",
    price: 10490,
    image: "/image/p20.jpeg",
    category: "oppo",
    details:
      "4 GB RAM | 64 GB ROM | Expandable Upto 512 GB 16.59 cm (6.53 inch) HD+ Display 13MP Rear Camera | 5MP Front Camera 5000 mAh Li-Polymer BatteryMediaTek Helio G25 Processor",
    image1: "/image/sm1.jpeg",
    image2: "/image/sm2.jpeg",
    image3: "/image/sm3.jpeg",
    image4: "/image/sm4.jpeg",
    quantity: 1,
  },
  {
    id: 21,
    title: "OPPO A53 (Moonlight Black, 128 GB)  (6 GB RAM)",
    price: 13990,
    image: "/image/p21.jpeg",
    category: "oppo",
    details:
      "4 GB RAM | 64 GB ROM | Expandable Upto 512 GB 16.59 cm (6.53 inch) HD+ Display 13MP Rear Camera | 5MP Front Camera 5000 mAh Li-Polymer BatteryMediaTek Helio G25 Processor",
    image1: "/image/sm1.jpeg",
    image2: "/image/sm2.jpeg",
    image3: "/image/sm3.jpeg",
    image4: "/image/sm4.jpeg",
    quantity: 1,
  },
  {
    id: 22,
    title: "vivo Y33s (Mirror Black, 128 GB)  (8 GB RAM)    ",
    price: 17990,
    image: "/image/p22.jpeg",
    category: "vivo",
    details:
      "4 GB RAM | 64 GB ROM | Expandable Upto 512 GB 16.59 cm (6.53 inch) HD+ Display 13MP Rear Camera | 5MP Front Camera 5000 mAh Li-Polymer BatteryMediaTek Helio G25 Processor",
    image1: "/image/sm1.jpeg",
    image2: "/image/sm2.jpeg",
    image3: "/image/sm3.jpeg",
    image4: "/image/sm4.jpeg",
    quantity: 1,
  },
  {
    id: 23,
    title: "vivo Y20A 2021 (Nebula Blue, 64 GB)  (3 GB RAM)",
    price: 11990,
    image: "/image/p23.jpeg",
    category: "vivo",
    details:
      "4 GB RAM | 64 GB ROM | Expandable Upto 512 GB 16.59 cm (6.53 inch) HD+ Display 13MP Rear Camera | 5MP Front Camera 5000 mAh Li-Polymer BatteryMediaTek Helio G25 Processor",
    image1: "/image/sm1.jpeg",
    image2: "/image/sm2.jpeg",
    image3: "/image/sm3.jpeg",
    image4: "/image/sm4.jpeg",
    quantity: 1,
  },
  {
    id: 24,
    title: "vivo Y21 (Midnight Blue, 64 GB)  (4 GB RAM)",
    price: 13990,
    image: "/image/p24.jpeg",
    category: "vivo",
    details:
      "4 GB RAM | 64 GB ROM | Expandable Upto 512 GB 16.59 cm (6.53 inch) HD+ Display 13MP Rear Camera | 5MP Front Camera 5000 mAh Li-Polymer BatteryMediaTek Helio G25 Processor",
    image1: "/image/sm1.jpeg",
    image2: "/image/sm2.jpeg",
    image3: "/image/sm3.jpeg",
    image4: "/image/sm4.jpeg",
    quantity: 1,
  },
];

export default ProductData;
